version: '3.8'

services:
  productapi:
    image: jovan141/productapi:latest
    container_name: productapi
    ports:
      - "5021:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      - mongo

  product-front:
    image: jovan141/product-front:latest
    container_name: product-front
    ports:
      - "80:8080"
    depends_on:
      - productapi
    deploy:
      update_config:
        image_pull_policy: always

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
