name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main  
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/deploy-to-azure.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Pull images from DockerHub
      run: |
        docker pull jovan141/productapi:latest
        docker pull jovan141/product-front:latest
        docker pull mongo:latest

    - name: Tag images for ACR
      run: |
        docker tag jovan141/productapi:latest ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/productapi:latest
        docker tag jovan141/product-front:latest ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/product-front:latest
        docker tag mongo:latest ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/mongo:latest

    - name: Push images to ACR
      run: |
        docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/productapi:latest
        docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/product-front:latest
        docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/mongo:latest

    - name: Deploy with Docker Compose
      run: |
        sed -i 's|jovan141/productapi:latest|${{ secrets.AZURE_ACR_NAME }}.azurecr.io/productapi:latest|g' docker-compose.yml
        sed -i 's|jovan141/product-front:latest|${{ secrets.AZURE_ACR_NAME }}.azurecr.io/product-front:latest|g' docker-compose.yml
        docker-compose -f docker-compose.yml up -d
