name: Frontend Docker Build and Push

on:
  push:
    paths:
      - 'frontend/product-app/**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd frontend/product-app
        docker build -t jovan141/product-fornt:latest .
        docker push jovan141/product-front:latest
